### ISSUE TITLE
Cleaner way to get a stack-trace?

### ISSUE THREAD

**Issue by mindplay-dk** [felixge/node-stack-trace#38]
Is there any way to get a stack-trace without modifying the global `Error` object in `get`?

I know the modifications are temporary, but it just rubs me the wrong way - it's a pretty small function, but as hard as I try, I can't understand how or why it works.

The [documentation](https://v8.dev/docs/stack-trace-api) is really sparse, and the example in the documentation didn't work for me - this library is the first and only implementation I've seen that actually works in Chrome.

If tampering with the static properties of `Error` is the only way to do it, then so be it - I'm just never confident having to use code that I can't explain and just wish there was a simpler way to do this. It seems odd that there wouldn't be... 🤔

**Comment by jasonk** [comment]
There isn't a reasonable way to get the CallSite information without tampering with Error, because the API provided by V8 to capture a stack trace is limited to just two static methods:

* `Error.captureStackTrace( error )`, which captures the CallSite information and attaches a `stack` property to the `error` that you passed it
* `Error.prepareStackTrace( error, structuredStackTrace )`, which is called by the property getter that was added by `captureStackTrace` to format the stack.  it takes the `error` and an array of `CallSite` objects and returns the formatted stack trace that gets returned when you access the `error.stack` property.

So what libraries like this one do in order to get those `CallSite` objects is to temporarily override `prepareStackTrace` with a function that does nothing except return the `structuredStackTrace` argument. Then when you call `captureStackTrace` on an object, the `stack` that gets attached to it isn't formatted into a string, it just ends up with the raw array of `CallSite` objects.

This is detailed here: https://v8.dev/docs/stack-trace-api#customizing-stack-traces

**Comment by mindplay-dk** [comment]
I see, yes - it's kind of wonky API... as though they didn't really intend for anyone to use it - or as though it's exposing an internal implementation detail. But it seems you're doing the best you can do with what they provided.

Thank you for the explanation. 🙂
